//
//  dummySeatDataList.swift
//  movieBookingApp
//
//  Created by Ye Yint Aung on 24/02/2022.
//

import Foundation

let seatData = [
    SeatVO(title: "A", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_EMPTY),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_EMPTY),
    SeatVO(title: "A", type: SEAT_TYPE_TITLE),
    SeatVO(title: "B", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "B", type: SEAT_TYPE_TITLE),
    SeatVO(title: "C", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "C", type: SEAT_TYPE_TITLE),
    SeatVO(title: "D", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_SELECTED),
    SeatVO(title: "", type: SEAT_TYPE_SELECTED),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "D", type: SEAT_TYPE_TITLE),
    SeatVO(title: "E", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_TAKEN),
    SeatVO(title: "", type: SEAT_TYPE_TAKEN),
    SeatVO(title: "", type: SEAT_TYPE_TAKEN),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "E", type: SEAT_TYPE_TITLE),
    SeatVO(title: "F", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "F", type: SEAT_TYPE_TITLE),
    SeatVO(title: "G", type: SEAT_TYPE_TITLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
    SeatVO(title: "G", type: SEAT_TYPE_TITLE)
]
